# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Insert Dreams Here' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Insert Dreams Here
    pod 'Parse'
    pod 'RSKPlaceholderTextView'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
  target 'Insert Dreams HereTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Insert Dreams HereUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
